    <footer>
      <div class="container">
        <div class="row">
          <div class="footer-col">
            <h4>Our Group Members</h4>
            <ul>
              <li>
                <a href="mailto:103500095@student.swin.edu.au"
                  >103500095 - Rox Nguyen</a
                >
              </li>
              <li>
                <a href="mailto:100583828@student.swin.edu.au"
                  >100583828 - Giovanni Tripodi</a
                >
              <li>
                <a href="mailto:103848151@student.swin.edu.au"
                  >103848151 - William Chan</a
                >
              </li>
              <li>
                <a href="mailto:103844094@student.swin.edu.au"
                  >103844094 - Tashahud</a
                >
              </li>
              <li>
                <a href="mailto:103793057@student.swin.edu.au"
                  >103793057 - Ahmed Daiyan</a
                >
              </li>
                <li>
                <a href="">OUR YOUTUBE VIDEO</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>