      <nav>
        <a href="index.php"
          ><img src="./Images/logo.png" alt="Webify logo"
        /></a>
        <div class="nav-links">
          <div class="menu-wrap">
            <input type="checkbox" class="toggler" />
            <div class="hamburger">
              <div></div>
            </div>
            <div class="menu">
              <div>
                <div>
                  <ul>
                    <li><a href="topic.php">TOPIC</a></li>
                    <li><a href="quiz.php">QUIZ</a></li>
                    <li><a href="manage.php">MANAGE</a></li>
                    <li><a href="enhancements.html">ENHANCEMENTS 1</a></li>
                    <li><a href="enhancements.php">ENHANCEMENTS 2</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>